replicaCount: 1

image:
  repository: acrdev8912.azurecr.io/payment-app
  tag: v4
service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

serviceAccount:
  create: true

ingress:
  enabled: false

autoscaling:
  enabled: false