replicaCount: 1

image:
  repository: acrdev8912.azurecr.io/payment-app
  tag: dc32f39c9ee7ce0db1381f3f9ad4a69117162ad6

service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

serviceAccount:
  create: true

ingress:
  enabled: false

autoscaling:
  enabled: false