replicaCount: 1

image:
  repository: acrdev8912.azurecr.io/payment-app
  tag: 599bc8f00c9b9ae99fc06ba019f2d3d4f21dfc7b
service:
  type: LoadBalancer
  port: 80
  targetPort: 5000

serviceAccount:
  create: true

ingress:
  enabled: false

autoscaling:
  enabled: false